#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

help () {
  cat <<-'EOF'
build
Scripts which packages pnpm into an AppImage binary.

Usage:
  ./build <version> <arch>
  ./build [-h|--help]

  <version>     Version of pnpm
  <arch>        Architecture to build, default to your arch
  -h, --help    Display this message

Example:
  ./build 6.9.1 x86_64
  ./build 6.10.0 aarch64
  ./build -h
  ./build --help
EOF
}

if (( $# == 0 )); then
  help
  exit 1
fi

if [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
  help
  exit
fi

VERSION="${1}"
ARCH="${2:-$(uname -m)}"

echo "pnpm, in a single file - ${VERSION} ${ARCH}"

if [[ "$ARCH" != 'x86_64' && "$ARCH" != 'aarch64' ]]; then
  echo 'Unsupported architecture specified! Arch should be x86_64 or aarch64.'
  exit 1
fi

# Reference: https://docs.appimage.org/packaging-guide/manual.html
mkdir -p pnpm.AppDir/usr/{lib,bin}

# Download AppImageKit
curl -L "https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-$(uname -m).AppImage" -o appimagetool
curl -L "https://github.com/AppImage/AppImageKit/releases/download/13/AppRun-${ARCH}" -o pnpm.AppDir/AppRun
curl -L "https://github.com/AppImage/AppImageKit/releases/download/13/runtime-${ARCH}" -o runtime
chmod +x appimagetool pnpm.AppDir/AppRun

# Download and extract pnpm
curl "https://registry.npmjs.org/pnpm/-/pnpm-${VERSION}.tgz" -o pnpm.tar.gz
tar -zxvf pnpm.tar.gz
mv package pnpm.AppDir/usr/lib/pnpm
cat <<'EOF' > pnpm.AppDir/usr/bin/pnpm
#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

DIR=$(readlink -e lib/pnpm/bin)
cd "${OWD}"
if [[ "$(basename "${ARGV0}")" == "pnpx" ]]; then
  exec "${DIR}/pnpx.cjs"
else
  exec "${DIR}/pnpm.cjs"
fi
EOF
chmod +x pnpm.AppDir/usr/bin/pnpm

# Reference: https://wiki.archlinux.org/index.php/desktop_entries
cat <<'EOF' > pnpm.AppDir/pnpm.desktop
[Desktop Entry]
Name=pnpm
Exec=pnpm
Icon=pnpm
Type=Application
Categories=Utility;ConsoleOnly;
Terminal=true
EOF

# Logo
cat <<'EOF' > pnpm.AppDir/pnpm.svg
<svg viewBox="76.5898724 44 164.0077551 164" xmlns="http://www.w3.org/2000/svg">
<g fill="#f9ad00"><path d="m237.6 95h-50v-50h50z"/><path d="m182.59
95h-50v-50h50z"/><path d="m127.59 95h-50v-50h50z"/><path d="m237.6
150h-50v-50h50z"/></g><path d="m182.59 150h-50v-50h50z" fill="#4e4e4e"/><path
d="m182.59 205h-50v-50h50z" fill="#4e4e4e"/><path d="m237.6 205h-50v-50h50z"
fill="#4e4e4e"/><path d="m127.59 205h-50v-50h50z" fill="#4e4e4e"/></svg>
EOF

# Package
./appimagetool -n pnpm.AppDir --runtime-file ./runtime
