#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

help () {
  cat <<-'EOF'
build
Scripts which packages pnpm into an AppImage binary.

Usage:
  ./build <version> [<arch>]
  ./build [-h|--help]

  <version>     Version of pnpm
  <arch>        Architecture to build, default to your arch
  -h, --help    Display this message

Example:
  ./build 6.9.1 x86_64
  ./build 6.10.0 aarch64
  ./build 6.9.0
  ./build -h
  ./build --help
EOF
}

if (( $# == 0 )); then
  help
  exit 1
fi

if [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
  help
  exit
fi

VERSION="${1}"
ARCH="${2:-$(uname -m)}"

echo "pnpm, in a single file - ${VERSION} ${ARCH}"

if [[ "$ARCH" != 'x86_64' && "$ARCH" != 'aarch64' ]]; then
  echo 'Unsupported architecture specified! Arch should be x86_64 or aarch64.'
  exit 1
fi

# Reference: https://docs.appimage.org/packaging-guide/manual.html
cp -R AppDir pnpm.AppDir

# Download AppImageKit
mkdir tmp
curl -L "https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-$(uname -m).AppImage" -o tmp/appimagetool
curl -L "https://github.com/AppImage/AppImageKit/releases/download/13/AppRun-${ARCH}" -o pnpm.AppDir/AppRun
curl -L "https://github.com/AppImage/AppImageKit/releases/download/13/runtime-${ARCH}" -o tmp/runtime
chmod +x tmp/appimagetool pnpm.AppDir/AppRun

# Download and extract pnpm
mkdir -p pnpm.AppDir/usr/lib/pnpm
curl "https://registry.npmjs.org/pnpm/-/pnpm-${VERSION}.tgz" |
  tar -zxC pnpm.AppDir/usr/lib/pnpm --strip-components=1

# Package
tmp/appimagetool -n pnpm.AppDir --runtime-file tmp/runtime
